spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/inventory
    username: root
    password: mysqlroot
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true 
  server:
  	servlet:
  	  contextPath: /inventory-api
  	port: 8020		